create extension if not exists pgcrypto;

create table if not exists public.events (
  id bigint generated by default as identity primary key,
  name text not null,
  slug text unique,
  status text not null default 'active',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.users (
  id uuid primary key,
  email text not null unique,
  name text not null,
  username text,
  role text not null default 'customer',
  staff_role text,
  department text,
  position text,
  status text not null default 'active',
  last_login_at timestamptz,
  last_login_ip text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists users_role_idx on public.users (role);
create index if not exists users_status_idx on public.users (status);

create table if not exists public.ticket_types (
  id bigint generated by default as identity primary key,
  event bigint references public.events(id),
  name text not null,
  price_type text not null default 'fixed',
  price numeric(10, 2),
  price_adj numeric(10, 2) not null default 0,
  weekdays text[] not null default array['Mon','Tue','Wed','Thu','Fri','Sat','Sun'],
  valid_from date,
  valid_to date,
  time_start time,
  time_end time,
  add_on text,
  remarks text,
  status text not null default 'enabled',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists ticket_types_event_idx on public.ticket_types (event);
create index if not exists ticket_types_status_idx on public.ticket_types (status);

create table if not exists public.slots (
  id bigint generated by default as identity primary key,
  event bigint references public.events(id),
  slot_date date not null,
  slot_time text not null,
  start_time time,
  end_time time,
  base_price numeric(10, 2),
  total_seats integer not null default 20,
  status text not null default 'active',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (event, slot_date, slot_time)
);

create index if not exists slots_date_idx on public.slots (slot_date);
create index if not exists slots_status_idx on public.slots (status);

create table if not exists public.orders (
  id uuid primary key default gen_random_uuid(),
  order_number text not null unique,
  slot_id text,
  slot_date date,
  slot_time text,
  customer_name text,
  customer_email text,
  customer_phone text,
  email_status text not null default 'not_sent',
  sales_channel text,
  order_status text not null default 'Pending',
  payment_status text,
  fulfillment_status text,
  payment_method text,
  payment_provider text,
  provider_reference text,
  ticket_quantity integer not null default 0,
  ticket_details jsonb not null default '[]'::jsonb,
  ticket_amount numeric(10, 2) not null default 0,
  addon_amount numeric(10, 2) not null default 0,
  platform_fee numeric(10, 2) not null default 0,
  payment_fee numeric(10, 2) not null default 0,
  gst numeric(10, 2) not null default 0,
  pst numeric(10, 2) not null default 0,
  coupon_discount numeric(10, 2) not null default 0,
  admin_adjustment numeric(10, 2) not null default 0,
  total_amount numeric(10, 2) not null default 0,
  coupon_code text,
  coupon_details jsonb not null default '{}'::jsonb,
  remarks text,
  created_by uuid,
  ip text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists orders_created_at_idx on public.orders (created_at);
create index if not exists orders_order_status_idx on public.orders (order_status);
create index if not exists orders_slot_date_idx on public.orders (slot_date);
create index if not exists orders_coupon_code_idx on public.orders (coupon_code);

create table if not exists public.tickets (
  id uuid primary key default gen_random_uuid(),
  ticket_number text unique,
  order_id uuid references public.orders(id) on delete cascade,
  slot_id text,
  verification_code text not null unique,
  slot_date date,
  slot_time text,
  ticket_type text,
  ticket_status text not null default 'Unused',
  qr_payload text,
  net_ticket_amount numeric(10, 2),
  original_ticket_amount numeric(10, 2),
  checked_in_at timestamptz,
  checked_in_by uuid,
  memo text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists tickets_order_id_idx on public.tickets (order_id);
create index if not exists tickets_created_at_idx on public.tickets (created_at);
create index if not exists tickets_slot_date_idx on public.tickets (slot_date);
create index if not exists tickets_ticket_status_idx on public.tickets (ticket_status);
create index if not exists tickets_ticket_type_idx on public.tickets (ticket_type);

create table if not exists public.coupons (
  id bigint generated by default as identity primary key,
  code text not null unique,
  source text not null default 'manual',
  discount_type text not null default 'percent',
  discount_value numeric(10, 2) not null,
  min_purchase numeric(10, 2) not null default 0,
  max_uses integer,
  used_count integer not null default 0,
  total_amount numeric(10, 2) not null default 0,
  valid_from date,
  valid_to date,
  remarks text,
  status text not null default 'active',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists coupons_status_idx on public.coupons (status);
create index if not exists coupons_source_idx on public.coupons (source);

create table if not exists public.marketing_settings (
  id boolean primary key default true,
  enabled boolean not null default false,
  send_delay_minutes integer not null default 45,
  coupon_validity_days integer not null default 30,
  discount_type text not null default 'percent',
  discount_value numeric(10, 2) not null default 5,
  min_purchase numeric(10, 2) not null default 0,
  max_uses integer not null default 9999,
  referral_enabled boolean not null default false,
  referral_reward numeric(10, 2) not null default 5,
  updated_at timestamptz not null default now(),
  constraint marketing_settings_single_row check (id)
);

create table if not exists public.marketing_records (
  id bigint generated by default as identity primary key,
  recipient_name text,
  recipient_email text,
  coupon_code text references public.coupons(code),
  order_id uuid references public.orders(id),
  status text not null default 'pending',
  coupon_used boolean not null default false,
  sent_at timestamptz,
  created_at timestamptz not null default now()
);

create index if not exists marketing_records_status_idx on public.marketing_records (status);
create index if not exists marketing_records_sent_at_idx on public.marketing_records (sent_at);

create table if not exists public.audit_logs (
  id bigint generated by default as identity primary key,
  admin_id uuid,
  admin_email text,
  admin_name text,
  action_type text not null,
  target_type text,
  target_id text,
  action_details jsonb not null default '{}'::jsonb,
  login_info text,
  created_at timestamptz not null default now()
);

create index if not exists audit_logs_created_at_idx on public.audit_logs (created_at);
create index if not exists audit_logs_action_type_idx on public.audit_logs (action_type);
