-- Admin setup for Supabase (SQL Editor).
-- Assumes public.users, public.slots, public.orders, and public.tickets already exist.
-- Then run 003_normalize_relations.sql to drop redundant columns and add FKs.
-- Safe to re-run.

create extension if not exists pgcrypto;

-- Extend existing tables
alter table public.users
  add column if not exists staff_role text,
  add column if not exists department text,
  add column if not exists position text,
  add column if not exists status text,
  add column if not exists last_login_at timestamptz,
  add column if not exists last_login_ip text;

alter table public.users
  drop constraint if exists users_role_check;

alter table public.users
  add constraint users_role_check
  check (role in ('owner', 'administrator', 'customer'));

alter table public.users
  drop column if exists username;

alter table public.orders
  add column if not exists email_status text,
  add column if not exists ip text;

-- New admin tables
create table if not exists public.events (
  id bigint generated by default as identity primary key,
  name text not null,
  slug text unique,
  status text not null,
  created_at timestamptz not null,
  updated_at timestamptz not null
);

create table if not exists public.ticket_types (
  id bigint generated by default as identity primary key,
  event bigint references public.events (id) on delete set null,
  name text not null,
  price_type text not null,
  price numeric(10, 2),
  price_adj numeric(10, 2) not null,
  weekdays text[] not null,
  valid_from date,
  valid_to date,
  time_start time,
  time_end time,
  add_on text,
  remarks text,
  status text not null,
  created_at timestamptz not null,
  updated_at timestamptz not null
);

create table if not exists public.coupons (
  id bigint generated by default as identity primary key,
  code text not null unique,
  source text not null,
  discount_type text not null,
  discount_value numeric(10, 2) not null,
  min_purchase numeric(10, 2) not null,
  max_uses integer,
  used_count integer not null,
  total_amount numeric(10, 2) not null,
  valid_from date,
  valid_to date,
  remarks text,
  status text not null,
  created_at timestamptz not null,
  updated_at timestamptz not null
);

create table if not exists public.marketing_settings (
  id boolean primary key,
  enabled boolean not null,
  send_delay_minutes integer not null,
  coupon_validity_days integer not null,
  discount_type text not null,
  discount_value numeric(10, 2) not null,
  min_purchase numeric(10, 2) not null,
  max_uses integer not null,
  referral_enabled boolean not null,
  referral_reward numeric(10, 2) not null,
  updated_at timestamptz not null,
  constraint marketing_settings_single_row check (id)
);

create table if not exists public.marketing_records (
  id bigint generated by default as identity primary key,
  recipient_name text,
  recipient_email text,
  coupon_code text references public.coupons (code) on delete set null,
  order_id uuid references public.orders (id) on delete set null,
  status text not null,
  coupon_used boolean not null,
  sent_at timestamptz,
  created_at timestamptz not null
);

create table if not exists public.audit_logs (
  id bigint generated by default as identity primary key,
  admin_id uuid references public.users (id) on delete set null,
  action_type text not null,
  target_type text,
  target_id text,
  action_details jsonb not null,
  login_info text,
  created_at timestamptz not null
);
