-- Resource-based scheduling and multi-item cart support.
-- Run after 001_admin_schema.sql, 002_admin_seed_catalog.sql, and 003_normalize_relations.sql.
-- Safe to re-run.
--
-- Business rules represented here:
--   - Terracotta Army VR uses HTC headsets and the VR Show Room.
--   - Panda VR and Dino VR use Pico headsets and the VR Show Room.
--   - Games A/B/C use Pico headsets and the Game Room.
--   - Pico headset inventory is shared across Panda/Dino/Games.
--   - Game Room capacity is 8, even though Pico inventory is 10.
--   - VR Show Room can run HTC-mode content or Pico-mode content at a time.
--     Backend must enforce that htc and pico vr_room_mode values do not overlap.
--   - Panda and Dino can overlap because both are Pico-mode, if capacity allows.
--   - Terracotta can overlap with games because games have vr_room_mode = 'none'.

create extension if not exists pgcrypto;

-- 1. Add event metadata used by availability and scheduling logic.
alter table public.events
  add column if not exists event_type text not null default 'vr_show',
  add column if not exists content_mode text not null default 'vr',
  add column if not exists headset_brand text,
  add column if not exists vr_room_mode text,
  add column if not exists duration_minutes integer;

-- 2. Physical / business resources with capacity limits.
create table if not exists public.resources (
  id bigint generated by default as identity primary key,
  code text not null unique,
  name text not null,
  resource_type text not null,
  capacity integer not null,
  status text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- 3. Which resources each event consumes per ticket/person.
create table if not exists public.event_resource_requirements (
  id bigint generated by default as identity primary key,
  event_id bigint not null references public.events (id) on delete cascade,
  resource_id bigint not null references public.resources (id) on delete cascade,
  units_per_ticket integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint event_resource_requirements_unique unique (event_id, resource_id)
);

-- 4. Slots are now for a specific event.
alter table public.slots
  add column if not exists event_id bigint references public.events (id) on delete set null;

-- 5. Multi-item shopping cart lines.
-- One order can contain multiple events, slots, and ticket types.
create table if not exists public.order_items (
  id uuid primary key default gen_random_uuid(),
  order_id uuid not null references public.orders (id) on delete cascade,
  event_id bigint not null references public.events (id),
  slot_id uuid not null references public.slots (id),
  ticket_type_id bigint references public.ticket_types (id) on delete set null,
  event_name text not null,
  slot_date date not null,
  slot_time text not null,
  ticket_type text not null,
  quantity integer not null,
  unit_price numeric(10, 2) not null,
  subtotal_amount numeric(10, 2) not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- 6. Tickets trace back to the cart item that generated them.
alter table public.tickets
  add column if not exists order_item_id uuid references public.order_items (id) on delete set null;

-- 7. Seed capacity resources.
-- Change vr_show_room capacity if the room cannot actually hold 20 people.
insert into public.resources (code, name, resource_type, capacity, status, created_at, updated_at)
values
  ('htc_headsets', 'HTC Headsets', 'headset_pool', 20, 'active', now(), now()),
  ('pico_headsets', 'Pico Headsets', 'headset_pool', 10, 'active', now(), now()),
  ('vr_show_room', 'VR Show Room', 'room', 20, 'active', now(), now()),
  ('game_room', 'Game Room', 'room', 8, 'active', now(), now())
on conflict (code) do update
set
  name = excluded.name,
  resource_type = excluded.resource_type,
  capacity = excluded.capacity,
  status = excluded.status,
  updated_at = now();

-- 8. Seed required events.
-- These rows are intentionally generic; admin screens can rename/display them later.
insert into public.events (name, slug, status, created_at, updated_at)
values
  ('Terracotta Army VR', 'terracotta-warriors', 'active', now(), now()),
  ('Panda VR', 'panda-vr', 'active', now(), now()),
  ('Dino VR', 'dino-vr', 'active', now(), now()),
  ('Game A', 'game-a', 'active', now(), now()),
  ('Game B', 'game-b', 'active', now(), now()),
  ('Game C', 'game-c', 'active', now(), now())
on conflict (slug) do update
set
  name = excluded.name,
  status = excluded.status,
  updated_at = now();

-- 9. Configure known event metadata.
-- Update the slug values below if production event slugs differ.
update public.events
set
  event_type = 'vr_show',
  content_mode = 'vr',
  headset_brand = 'htc',
  vr_room_mode = 'htc',
  duration_minutes = coalesce(duration_minutes, 45),
  updated_at = now()
where slug in ('terracotta-warriors', 'terracotta-army-vr', 'terracotta-warriors-vr');

update public.events
set
  event_type = 'vr_show',
  content_mode = 'vr',
  headset_brand = 'pico',
  vr_room_mode = 'pico',
  duration_minutes = coalesce(duration_minutes, 12),
  updated_at = now()
where slug in ('panda-vr', 'dino-vr');

update public.events
set
  event_type = 'game',
  content_mode = 'game',
  headset_brand = 'pico',
  vr_room_mode = 'none',
  duration_minutes = coalesce(duration_minutes, 12),
  updated_at = now()
where slug in ('game-a', 'game-b', 'game-c');

-- 10. Resource consumption rules.
-- Terracotta consumes HTC headsets and VR Show Room capacity.
insert into public.event_resource_requirements (
  event_id,
  resource_id,
  units_per_ticket,
  created_at,
  updated_at
)
select e.id, r.id, 1, now(), now()
from public.events e
join public.resources r on r.code in ('htc_headsets', 'vr_show_room')
where e.slug in ('terracotta-warriors', 'terracotta-army-vr', 'terracotta-warriors-vr')
on conflict (event_id, resource_id) do update
set
  units_per_ticket = excluded.units_per_ticket,
  updated_at = now();

-- Panda and Dino consume Pico headsets and VR Show Room capacity.
insert into public.event_resource_requirements (
  event_id,
  resource_id,
  units_per_ticket,
  created_at,
  updated_at
)
select e.id, r.id, 1, now(), now()
from public.events e
join public.resources r on r.code in ('pico_headsets', 'vr_show_room')
where e.slug in ('panda-vr', 'dino-vr')
on conflict (event_id, resource_id) do update
set
  units_per_ticket = excluded.units_per_ticket,
  updated_at = now();

-- Games consume Pico headsets and Game Room capacity.
insert into public.event_resource_requirements (
  event_id,
  resource_id,
  units_per_ticket,
  created_at,
  updated_at
)
select e.id, r.id, 1, now(), now()
from public.events e
join public.resources r on r.code in ('pico_headsets', 'game_room')
where e.slug in ('game-a', 'game-b', 'game-c')
on conflict (event_id, resource_id) do update
set
  units_per_ticket = excluded.units_per_ticket,
  updated_at = now();

-- 11. Indexes for availability, checkout, and webhook/payment lookups.
create index if not exists idx_slots_event_time
  on public.slots (event_id, business_date, start_time, end_time);

create index if not exists idx_slots_business_time
  on public.slots (business_date, start_time, end_time);

create index if not exists idx_orders_provider_reference
  on public.orders (payment_provider, provider_reference);

create index if not exists idx_order_items_order_id
  on public.order_items (order_id);

create index if not exists idx_order_items_slot_id
  on public.order_items (slot_id);

create index if not exists idx_order_items_event_slot
  on public.order_items (event_id, slot_id);

create index if not exists idx_tickets_order_item_id
  on public.tickets (order_item_id);

create index if not exists idx_event_resource_requirements_event_id
  on public.event_resource_requirements (event_id);
